/**********************************************/
/* Author           : Naveenkumar N           */
/* Date             : 30-10-2019              */
/* Filename         : Makefile                */
/* Description      : Makefile                */
/**********************************************/

obj-m:=hlo_world.o
